name: metabolomics_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - matplotlib
  - openpyxl
  - cobra
  - swiglpk
  - pip
  - pip:
      - escher
