"""
06_figures.py — clone flux-comparison figures

Main figures generated here:
  Fig 1. IgG titer time course
  Fig 2. Exchange-rate heatmap
  Fig 3. Lactate/glucose phenotype
  Fig 5. High vs Low exchange-rate comparison
  Fig 8. Summary panel focused on clone flux-comparison workflow

Notes:
  - Fig 4 was intentionally removed. Direct DM_igg_g/DM_for_igg objective ranking
    is treated as a diagnostic table, not a main figure.
  - KO screening is optional and is not included in the main summary because it is
    often uninformative for this clone-comparison demo.
  - Central/mAb pathway figures are generated by step 14 as Fig10/Fig11.
"""
import sys, os, argparse, warnings, pickle
warnings.filterwarnings("ignore")

def _find_root():
    cur = os.path.dirname(os.path.abspath(__file__))
    for _ in range(5):
        if os.path.exists(os.path.join(cur, 'src', 'config.py')):
            return cur
        cur = os.path.dirname(cur)
    return cur

ROOT = _find_root()
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from src.config import *
from src.fba_utils import save_figure

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats

parser = argparse.ArgumentParser()
parser.add_argument("--dataset", default="practice_20aa", choices=["sowa2020", "practice_20aa", "own_experiment"])
parser.add_argument("--analysis_mode", default=os.environ.get("CHO_ANALYSIS_MODE", "both"), choices=["predict", "explain", "both"])
args = parser.parse_args()
DATASET = args.dataset

print("=" * 60)
print(f"  06_figures.py — {DATASET} (clone flux-comparison figures)")
print("=" * 60)

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 9,
    "axes.labelsize": 10,
    "axes.titlesize": 10,
    "axes.titleweight": "bold",
    "axes.linewidth": 0.8,
    "xtick.labelsize": 8.5,
    "ytick.labelsize": 8.5,
    "legend.fontsize": 8,
    "legend.framealpha": 0.85,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "lines.linewidth": 1.5,
    "patch.linewidth": 0.6,
})

P = PALETTE

pkl_path = os.path.join(DATA_PROCESSED, f"rates_{DATASET}.pkl")
if not os.path.exists(pkl_path):
    print(f"  !! {pkl_path} 없음 — step 1 먼저 실행")
    sys.exit(1)
with open(pkl_path, "rb") as f:
    data = pickle.load(f)

df_raw          = data["df_raw"]
all_rates       = data["all_rates"]
all_constraints = data["all_constraints"]
igG_day14       = data.get("igG_day14", {})
high_clones     = data.get("high_clones", [])
low_clones      = data.get("low_clones", [])
sorted_clones   = data.get("sorted_clones", data.get("clones", []))
clones          = data.get("clones", sorted_clones)
COL2NAME        = data.get("COL2NAME", {})
MET_COLS        = data.get("MET_COLS", [])
OBJ_LABEL       = data.get("objective", data.get("selected_objective", OBJ_RXN))
CONSTRAINT_POLICY_USED = data.get("constraint_policy", "unknown")

# Remove stale main figures that were intentionally retired.
for _old in ["Fig4_fba_results.png", "Fig7_ko_screen.png"]:
    _old_path = os.path.join(results_dir(DATASET, "figures"), _old)
    if os.path.exists(_old_path):
        try:
            os.remove(_old_path)
            print(f"  removed retired figure: {_old}")
        except Exception:
            pass

clone_colors = {}
for i, c in enumerate(clones):
    if c in high_clones:
        clone_colors[c] = P["high"]
    elif c in low_clones:
        clone_colors[c] = P["low"]
    else:
        clone_colors[c] = P["mid"][i % len(P["mid"])]

def ax_grid(ax):
    ax.xaxis.grid(True, ls=":", color="0.88")
    ax.yaxis.grid(True, ls=":", color="0.88")
    ax.set_axisbelow(True)

def get_lac_glc_df():
    G = "EX_glc_e"; L = "EX_lac_L_e"
    rows = []
    for clone, cst in all_constraints.items():
        glc = abs(min(cst.get(G, (0, 0))))
        lac_lb, lac_ub = cst.get(L, (0, 0))
        lac = lac_ub if lac_ub > 0 else lac_lb
        ratio = lac / glc if glc > 0 else 0
        rows.append({"clone": clone, "lac_glc": ratio, "igG": igG_day14.get(clone, 0)})
    return pd.DataFrame(rows).sort_values("igG", ascending=False)

def get_high_low_rates():
    high_avg = {col: np.mean([all_rates[c][col]["rate_mmol_gDCWh"] for c in high_clones if c in all_rates and col in all_rates[c]]) for col in MET_COLS}
    low_avg  = {col: np.mean([all_rates[c][col]["rate_mmol_gDCWh"] for c in low_clones if c in all_rates and col in all_rates[c]]) for col in MET_COLS}
    diffs = {c: abs(high_avg.get(c, 0) - low_avg.get(c, 0)) for c in MET_COLS}
    sorted_mets = sorted(diffs, key=diffs.get, reverse=True)
    return high_avg, low_avg, sorted_mets

# Fig 1
print("  Fig 1: IgG timecourse...")
try:
    fig, ax = plt.subplots(figsize=(9, 5))
    for clone in sorted_clones:
        sub = df_raw[df_raw["Sample ID"] == clone].sort_values("DAY")
        lw  = 2.5 if clone in high_clones else (1.0 if clone in low_clones else 1.5)
        ls  = "-" if clone in high_clones else (":" if clone in low_clones else "--")
        ms  = 7 if clone in (high_clones + low_clones) else 5
        ax.plot(sub["DAY"], sub["IgG"], color=clone_colors[clone], lw=lw, ls=ls, marker="o", ms=ms, label=clone, zorder=3)
    ax.set_xlabel("Culture Day")
    ax.set_ylabel("IgG Titer (mg/L)")
    ax.set_title(f"Figure 1. IgG Production Time Course\n(Red=High producer top {len(high_clones)}, Blue=Low producer bottom {len(low_clones)})")
    ax_grid(ax)
    ax.legend(loc="upper left", ncol=2, fontsize=8)
    for clone in high_clones + low_clones:
        sub = df_raw[df_raw["Sample ID"] == clone]
        if len(sub) == 0:
            continue
        last = sub.loc[sub["DAY"].idxmax()]
        ax.annotate(f"{last['IgG']:.0f}", xy=(last["DAY"], last["IgG"]), xytext=(4, 0), textcoords="offset points", fontsize=7.5, color=clone_colors[clone], va="center")
    plt.tight_layout()
    save_figure(fig, "Fig1_IgG_timecourse.png", DATASET)
except Exception as e:
    print(f"  !! Fig 1 오류: {e}")

# Fig 2
print("  Fig 2: Exchange rate heatmap...")
try:
    rate_matrix = pd.DataFrame({clone: {COL2NAME.get(col, col): info["rate_mmol_gDCWh"] for col, info in rates.items()} for clone, rates in all_rates.items()}).T
    rate_matrix = rate_matrix.loc[sorted(rate_matrix.index, key=lambda c: igG_day14.get(c, 0), reverse=True)]
    fig, ax = plt.subplots(figsize=(max(12, len(MET_COLS) * 0.7), 5))
    sns.heatmap(rate_matrix, ax=ax, cmap="RdBu_r", center=0, annot=True, fmt=".3f", linewidths=0.4, linecolor="white", cbar_kws={"label": "Rate (mmol/gDCW/h)\nneg=uptake, pos=secretion", "shrink": 0.7}, annot_kws={"size": 7.5})
    ax.set_title(f"Figure 2. Exchange Rate Heatmap\n(Day {data['day_interval'][0]}→{data['day_interval'][1]}, feed-corrected, sorted by IgG titer)")
    ax.set_xlabel("Metabolite")
    ax.set_ylabel("Clone (sorted by IgG)")
    ax.tick_params(axis="x", rotation=45)
    ax.tick_params(axis="y", rotation=0)
    plt.tight_layout()
    save_figure(fig, "Fig2_rate_heatmap.png", DATASET)
except Exception as e:
    print(f"  !! Fig 2 오류: {e}")

# Fig 3
print("  Fig 3: Lac/Glc ratio...")
try:
    lgdf = get_lac_glc_df()
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))
    ax = axes[0]
    bars = ax.bar(lgdf["clone"], lgdf["lac_glc"], color=[clone_colors[c] for c in lgdf["clone"]], edgecolor="k", lw=0.5, zorder=3)
    ax.axhline(0.0, color="k", lw=1, ls="--", label="0 = no net lactate")
    ax.set_ylabel("Apparent Lac/Glc Ratio (mmol/mmol)")
    ax.set_title("(A) Lac/Glc Ratio per Clone\n(negative = lactate consumption)")
    ax.tick_params(axis="x", rotation=35)
    ax_grid(ax); ax.legend(fontsize=8)
    for bar, v in zip(bars, lgdf["lac_glc"]):
        ax.text(bar.get_x()+bar.get_width()/2, v + (0.01 if v >= 0 else -0.01), f"{v:.2f}", ha="center", va="bottom" if v >= 0 else "top", fontsize=7.5)
    ax = axes[1]
    ax.scatter(lgdf["lac_glc"], lgdf["igG"], c=[clone_colors[c] for c in lgdf["clone"]], s=80, edgecolors="k", lw=0.5, zorder=3)
    if len(lgdf) > 2:
        sl, ic, r, p, _ = stats.linregress(lgdf["lac_glc"], lgdf["igG"])
        x_line = np.linspace(lgdf["lac_glc"].min(), lgdf["lac_glc"].max(), 50)
        ax.plot(x_line, sl*x_line + ic, "k--", lw=1.2, alpha=0.7, label=f"r={r:.2f}, p={p:.3f}")
        ax.legend(fontsize=8)
    for _, row in lgdf.iterrows():
        ax.annotate(row["clone"], (row["lac_glc"], row["igG"]), xytext=(4,2), textcoords="offset points", fontsize=7.5)
    ax.set_xlabel("Lac/Glc Ratio")
    ax.set_ylabel("IgG Day 14 (mg/L)")
    ax.set_title("(B) Lac/Glc Ratio vs IgG Titer")
    ax_grid(ax)
    fig.suptitle("Figure 3. Lactate/Glucose Behavior — measured exchange", fontsize=11, fontweight="bold")
    plt.tight_layout()
    save_figure(fig, "Fig3_lac_glc_ratio.png", DATASET)
except Exception as e:
    print(f"  !! Fig 3 오류: {e}")

print("  Fig 4: skipped intentionally (direct FBA objective diagnostic removed from main figures)")

# Fig 5
print("  Fig 5: High vs Low exchange rates...")
try:
    high_avg, low_avg, sorted_mets = get_high_low_rates()
    met_labels = [COL2NAME.get(m, m) for m in sorted_mets]
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    y = np.arange(len(sorted_mets)); w = 0.36
    vh = [high_avg.get(m, 0) for m in sorted_mets]
    vl = [low_avg.get(m, 0) for m in sorted_mets]
    axes[0].barh(y + w/2, vh, w, color=P["high"], label=f"High (n={len(high_clones)})", edgecolor="k", lw=0.4, zorder=3)
    axes[0].barh(y - w/2, vl, w, color=P["low"], label=f"Low (n={len(low_clones)})", edgecolor="k", lw=0.4, zorder=3)
    axes[0].set_yticks(y); axes[0].set_yticklabels(met_labels, fontsize=8.5)
    axes[0].axvline(0, color="k", lw=0.8)
    axes[0].set_xlabel("Exchange Rate (mmol/gDCW/h)\n(neg=uptake, pos=secretion)")
    axes[0].set_title("(A) High vs Low Producer")
    axes[0].legend(); ax_grid(axes[0])
    delta = [high_avg.get(m, 0) - low_avg.get(m, 0) for m in sorted_mets]
    axes[1].barh(y, delta, color=[P["high"] if d > 0 else P["low"] for d in delta], edgecolor="k", lw=0.4, zorder=3)
    axes[1].axvline(0, color="k", lw=0.8)
    axes[1].set_yticks(y); axes[1].set_yticklabels(met_labels, fontsize=8.5)
    axes[1].set_xlabel("Delta Rate = High - Low (mmol/gDCW/h)")
    axes[1].set_title("(B) Difference (High - Low)")
    axes[1].legend(handles=[mpatches.Patch(color=P["high"], label="Higher in High"), mpatches.Patch(color=P["low"], label="Lower in High")], loc="lower right")
    ax_grid(axes[1])
    fig.suptitle(f"Figure 5. Exchange Rate Comparison: High vs Low Producer\n(High={high_clones}, Low={low_clones})", fontsize=11, fontweight="bold")
    plt.tight_layout()
    save_figure(fig, "Fig5_high_vs_low_rates.png", DATASET)
except Exception as e:
    print(f"  !! Fig 5 오류: {e}")

# Fig 8 summary without Fig4/KO
print("  Fig 8: Summary panel without direct objective/KO panels...")
try:
    high_avg, low_avg, sorted_mets = get_high_low_rates()
    lgdf2 = get_lac_glc_df()
    fig = plt.figure(figsize=(14, 10))
    gs = fig.add_gridspec(2, 2, hspace=0.48, wspace=0.35)

    ax = fig.add_subplot(gs[0,0])
    for clone in sorted_clones:
        sub = df_raw[df_raw["Sample ID"] == clone].sort_values("DAY")
        lw = 2.2 if clone in high_clones else (1.0 if clone in low_clones else 1.2)
        ls = "-" if clone in high_clones else (":" if clone in low_clones else "--")
        ax.plot(sub["DAY"], sub["IgG"], color=clone_colors[clone], lw=lw, ls=ls, marker="o", ms=4, label=clone, zorder=3)
    ax.set_xlabel("Day"); ax.set_ylabel("IgG (mg/L)"); ax.set_title("(A) IgG time course")
    ax_grid(ax); ax.legend(fontsize=6, ncol=2)

    ax = fig.add_subplot(gs[0,1])
    bars = ax.bar(lgdf2["clone"], lgdf2["lac_glc"], color=[clone_colors.get(c, P["neutral"]) for c in lgdf2["clone"]], edgecolor="k", lw=0.5, zorder=3)
    ax.axhline(0.0, color="k", lw=1, ls="--")
    ax.set_ylabel("Apparent Lac/Glc Ratio")
    ax.set_title("(B) Lactate/glucose phenotype")
    ax.tick_params(axis="x", rotation=35); ax_grid(ax)

    ax = fig.add_subplot(gs[1,0])
    top8 = sorted_mets[:8]; yd = np.arange(len(top8)); wd = 0.32
    top8_labs = [COL2NAME.get(m, m) for m in top8]
    ax.barh(yd + wd/2, [high_avg.get(m,0) for m in top8], wd, color=P["high"], label=f"High (n={len(high_clones)})", edgecolor="k", lw=0.4, zorder=3)
    ax.barh(yd - wd/2, [low_avg.get(m,0) for m in top8], wd, color=P["low"], label=f"Low (n={len(low_clones)})", edgecolor="k", lw=0.4, zorder=3)
    ax.set_yticks(yd); ax.set_yticklabels(top8_labs, fontsize=8)
    ax.axvline(0, color="k", lw=0.8)
    ax.set_xlabel("Rate (mmol/gDCW/h)")
    ax.set_title("(C) High vs Low exchange constraints")
    ax.legend(fontsize=8); ax_grid(ax)

    ax = fig.add_subplot(gs[1,1])
    tables_dir = results_dir(DATASET, "tables")
    delta_file = os.path.join(tables_dir, "central_mab_flux_delta_high_low_measured_demand.csv")
    if not os.path.exists(delta_file):
        delta_file = os.path.join(tables_dir, "central_mab_flux_delta_high_low_no_igg_input.csv")
    if os.path.exists(delta_file):
        d = pd.read_csv(delta_file).sort_values("abs_delta", ascending=False).head(10).iloc[::-1]
        labels = (d["pathway"].astype(str) + " | " + d["label"].astype(str)).tolist()
        ax.barh(labels, d["delta_high_minus_low"], color=[P["high"] if x > 0 else P["low"] for x in d["delta_high_minus_low"]], edgecolor="k", lw=0.4, zorder=3)
        ax.axvline(0, color="k", lw=0.8)
        ax.set_xlabel("Flux delta = High - Low")
        ax.set_title("(D) Central/mAb pathway flux differences")
        ax_grid(ax)
    else:
        ax.axis("off")
        ax.text(0.02, 0.80, "Central/mAb pathway flux comparison", fontsize=12, fontweight="bold", transform=ax.transAxes)
        ax.text(0.02, 0.58, "Run step 14 before step 6 to embed Fig10/Fig11-derived\nflux-delta information here.", fontsize=9, transform=ax.transAxes)
        ax.text(0.02, 0.36, "Recommended: --steps 1,2,3,10,12,13,14,6", fontsize=9, transform=ax.transAxes)

    day_s, day_e = data.get("day_interval", (3,7))
    fig.suptitle(f"CHO Fed-Batch Clone Flux-Comparison Summary — {DATASET}\n"
                 f"iCHO3K prod model | constraints={CONSTRAINT_POLICY_USED} | Day {day_s}→{day_e} rates | High={high_clones} | Low={low_clones}",
                 fontsize=12, fontweight="bold", y=0.99)
    save_figure(fig, "Fig8_summary_panel.png", DATASET)
except Exception as e:
    print(f"  !! Fig 8 오류: {e}")

fig_dir = results_dir(DATASET, "figures")
pngs = sorted(f for f in os.listdir(fig_dir) if f.endswith(".png"))
print(f"\n  [생성된 Figure — results/{DATASET}/figures/]")
for f in pngs:
    sz = os.path.getsize(os.path.join(fig_dir, f)) // 1024
    print(f"    {f:<45s} ({sz:>4d} KB)")
print(f"\n  OK  06_figures 완료 — {len(pngs)}개 Figure 생성")
