
"""
16_batch_pathway_pfba_fva.py

Purpose
-------
Run interval-wise exchange-constrained FBA/pFBA and pathway-level FVA
using pathway reaction sets generated by 15_model_pathway_scout.py.

This script separates:
  A) measured / feed-corrected exchange phenotype
  B) model feasibility
  C) model-inferred pathway phenotype

Outputs
-------
results/tables/pathway/pathway_interval_summary.csv
results/tables/pathway/pathway_reaction_fluxes.csv
results/tables/pathway/pathway_reaction_fva.csv
results/tables/pathway/pathway_clone_summary.csv

Run
---
cd C:\CHO_POC_ChatGPT_260519

python scripts\16_batch_pathway_pfba_fva.py ^
  --base C:\CHO_POC_ChatGPT_260519 ^
  --rates-file data\metabolomics\processed\exchange_rates_feed_corrected.csv ^
  --pathway-file results\tables\pathway_reaction_sets.csv ^
  --mode relaxed ^
  --run-fva

If you find a meaningful objective in objective_candidates.csv:
  add --objective <reaction_id> --fraction 0.9
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import cobra
import pandas as pd
from cobra.flux_analysis import pfba, flux_variability_analysis


DEFAULT_OPEN = {
    "EX_h_e": (-1000, 1000),
    "EX_h2o_e": (-1000, 1000),
    "EX_o2_e": (-1000, 1000),
    "EX_co2_e": (-1000, 1000),
    "EX_hco3_e": (-1000, 1000),
    "EX_pi_e": (-1000, 1000),
    "EX_so4_e": (-1000, 1000),
}


def safe_name(x: object) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x)).strip("_") or "condition"


def pick_model(base: Path, model_file: str | None) -> Path:
    if model_file:
        p = Path(model_file)
        return p if p.is_absolute() else base / p
    candidates = [
        base / "model" / "iCHO3K-main" / "iCHO3K" / "Model" / "iCHO3K_cho_prod_generic_unblocked.json",
        base / "model" / "iCHO3K-main" / "iCHO3K" / "Model" / "iCHO3K_cho_prod_generic_unblocked.xml",
    ]
    for p in candidates:
        if p.exists():
            return p
    raise FileNotFoundError("Model file not found. Use --model-file")


def load_model(model_file: Path):
    if model_file.suffix.lower() == ".json":
        return cobra.io.load_json_model(str(model_file))
    return cobra.io.read_sbml_model(str(model_file))


def finite_number(x) -> bool:
    try:
        return math.isfinite(float(x))
    except Exception:
        return False


def set_bounds(rxn, lb, ub):
    if lb > ub:
        lb, ub = ub, lb
    lb = max(float(lb), -1000.0)
    ub = min(float(ub), 1000.0)
    if lb > ub:
        raise ValueError(f"Invalid bounds after clamp: {lb}, {ub}")
    rxn.bounds = (lb, ub)


def strict_bounds(row, buffer=0.20):
    lb, ub = row.get("lower_bound"), row.get("upper_bound")
    if finite_number(lb) and finite_number(ub):
        lb, ub = float(lb), float(ub)
    else:
        rate = row.get("rate")
        if not finite_number(rate):
            return None
        rate = float(rate)
        if rate < 0:
            lb, ub = rate * (1 + buffer), rate * (1 - buffer)
        else:
            lb, ub = rate * (1 - buffer), rate * (1 + buffer)
    if lb > ub:
        lb, ub = ub, lb
    return lb, ub


def relaxed_bounds(row, multiplier=10.0):
    rate = row.get("rate")
    if not finite_number(rate):
        return None
    rate = float(rate)
    if rate < 0:
        return rate * multiplier, 0.0
    if rate > 0:
        return 0.0, rate * multiplier
    return 0.0, 0.0


def apply_exchange_constraints(model, interval_df, mode, bound_buffer=0.20, relax_multiplier=10.0):
    applied = []
    warnings = []

    for rid, (lb, ub) in DEFAULT_OPEN.items():
        if rid in model.reactions:
            try:
                set_bounds(model.reactions.get_by_id(rid), lb, ub)
            except Exception as e:
                warnings.append({"reaction": rid, "issue": "default_open_failed", "detail": str(e)})

    interval_df = interval_df.drop_duplicates(subset=["exchange_rxn"], keep="last").copy()

    for _, row in interval_df.iterrows():
        rid = str(row.get("exchange_rxn", "")).strip()
        if not rid or rid not in model.reactions:
            warnings.append({"reaction": rid, "issue": "reaction_missing", "metabolite": row.get("metabolite", "")})
            continue

        b = strict_bounds(row, bound_buffer) if mode == "strict" else relaxed_bounds(row, relax_multiplier)
        if b is None:
            warnings.append({"reaction": rid, "issue": "invalid_bounds_or_rate", "metabolite": row.get("metabolite", "")})
            continue

        try:
            rxn = model.reactions.get_by_id(rid)
            set_bounds(rxn, *b)
            applied.append({
                "reaction": rid,
                "metabolite": row.get("metabolite", ""),
                "rate": row.get("rate", ""),
                "day_start": row.get("day_start", ""),
                "day_end": row.get("day_end", ""),
                "lower_bound": rxn.lower_bound,
                "upper_bound": rxn.upper_bound,
                "mode": mode,
            })
        except Exception as e:
            warnings.append({"reaction": rid, "issue": "set_bounds_failed", "detail": str(e), "metabolite": row.get("metabolite", "")})

    return pd.DataFrame(applied), pd.DataFrame(warnings)


def load_pathway_sets(pathway_file: Path, model) -> pd.DataFrame:
    df = pd.read_csv(pathway_file)
    if "include" in df.columns:
        include = df["include"].astype(str).str.lower().isin(["true", "1", "yes", "y"])
        df = df[include].copy()

    required = {"pathway", "reaction"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"pathway file missing columns: {missing}")

    df["reaction"] = df["reaction"].astype(str)
    df = df[df["reaction"].isin([r.id for r in model.reactions])].copy()
    return df.drop_duplicates(subset=["pathway", "reaction"])


def summarize_pathways(pathway_df: pd.DataFrame, flux_series: pd.Series, condition, d0, d1, mode, fba_status, obj_value):
    rows = []
    for pathway, sub in pathway_df.groupby("pathway"):
        rxns = list(sub["reaction"])
        values = pd.to_numeric(flux_series.reindex(rxns), errors="coerce").fillna(0.0)
        rows.append({
            "condition": condition,
            "day_start": d0,
            "day_end": d1,
            "interval": f"{float(d0):g}-{float(d1):g}",
            "mode": mode,
            "pathway": pathway,
            "n_reactions": len(rxns),
            "fba_status": fba_status,
            "objective_value": obj_value,
            "pfba_sum_abs_flux": values.abs().sum(),
            "pfba_mean_abs_flux": values.abs().mean() if len(values) else 0,
            "pfba_net_flux": values.sum(),
            "pfba_positive_flux_sum": values[values > 0].sum(),
            "pfba_negative_flux_sum": values[values < 0].sum(),
            "pfba_nonzero_reactions": int((values.abs() > 1e-9).sum()),
        })
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--rates-file", required=True)
    ap.add_argument("--pathway-file", default="results/tables/pathway_reaction_sets.csv")
    ap.add_argument("--model-file", default=None)
    ap.add_argument("--objective", default=None)
    ap.add_argument("--conditions", nargs="*", default=None)
    ap.add_argument("--mode", choices=["strict", "relaxed", "strict_then_relaxed"], default="relaxed")
    ap.add_argument("--bound-buffer", type=float, default=0.20)
    ap.add_argument("--relax-multiplier", type=float, default=10.0)
    ap.add_argument("--run-fva", action="store_true")
    ap.add_argument("--fraction", type=float, default=0.0, help="0.0 means FVA over feasible space; use 0.9 with meaningful objective")
    args = ap.parse_args()

    base = Path(args.base)
    model_file = pick_model(base, args.model_file)

    rates_path = Path(args.rates_file)
    if not rates_path.is_absolute():
        rates_path = base / rates_path

    pathway_file = Path(args.pathway_file)
    if not pathway_file.is_absolute():
        pathway_file = base / pathway_file

    outdir = base / "results" / "tables" / "pathway"
    outdir.mkdir(parents=True, exist_ok=True)

    rates = pd.read_csv(rates_path)
    rates["day_start"] = pd.to_numeric(rates["day_start"], errors="coerce")
    rates["day_end"] = pd.to_numeric(rates["day_end"], errors="coerce")
    rates = rates.dropna(subset=["condition", "day_start", "day_end", "exchange_rxn"]).copy()

    if args.conditions:
        keep = set(map(str, args.conditions))
        rates = rates[rates["condition"].astype(str).isin(keep)].copy()

    base_model = load_model(model_file)
    pathway_df = load_pathway_sets(pathway_file, base_model)

    print("[INFO] model:", model_file)
    print("[INFO] rates:", rates_path)
    print("[INFO] pathway file:", pathway_file)
    print("[INFO] pathway reactions:", len(pathway_df))
    print(pathway_df.groupby("pathway")["reaction"].nunique().sort_values(ascending=False).to_string())

    intervals = (
        rates[["condition", "day_start", "day_end"]]
        .drop_duplicates()
        .sort_values(["condition", "day_start", "day_end"])
        .reset_index(drop=True)
    )

    interval_rows = []
    reaction_flux_rows = []
    fva_rows = []
    applied_all = []
    warnings_all = []

    for _, iv in intervals.iterrows():
        cond = str(iv["condition"])
        d0 = float(iv["day_start"])
        d1 = float(iv["day_end"])
        sub = rates[
            (rates["condition"].astype(str) == cond)
            & (rates["day_start"] == d0)
            & (rates["day_end"] == d1)
        ].copy()

        selected_modes = [args.mode] if args.mode in ["strict", "relaxed"] else ["strict", "relaxed"]
        used = False

        for mode in selected_modes:
            model = load_model(model_file)
            if args.objective:
                if args.objective not in model.reactions:
                    raise ValueError(f"Objective not found in model: {args.objective}")
                model.objective = args.objective

            applied, warnings = apply_exchange_constraints(
                model, sub, mode,
                bound_buffer=args.bound_buffer,
                relax_multiplier=args.relax_multiplier,
            )

            sol = model.optimize()
            status = sol.status
            obj_value = sol.objective_value

            if args.mode == "strict_then_relaxed" and mode == "strict" and status != "optimal":
                print(f"[RUN] {cond} {d0:g}-{d1:g} strict={status}; retry relaxed")
                warnings["condition"] = cond
                warnings["day_start"] = d0
                warnings["day_end"] = d1
                warnings["mode"] = mode
                warnings_all.append(warnings)
                continue

            used = True
            print(f"[RUN] {cond} {d0:g}-{d1:g} mode={mode} status={status} obj={obj_value}")

            applied["condition"] = cond
            applied["day_start_interval"] = d0
            applied["day_end_interval"] = d1
            applied_all.append(applied)

            warnings["condition"] = cond
            warnings["day_start"] = d0
            warnings["day_end"] = d1
            warnings["mode"] = mode
            warnings_all.append(warnings)

            if status != "optimal":
                interval_rows.append({
                    "condition": cond,
                    "day_start": d0,
                    "day_end": d1,
                    "interval": f"{d0:g}-{d1:g}",
                    "mode": mode,
                    "pathway": "MODEL",
                    "n_reactions": 0,
                    "fba_status": status,
                    "objective_value": obj_value,
                    "pfba_sum_abs_flux": None,
                    "pfba_mean_abs_flux": None,
                    "pfba_net_flux": None,
                    "pfba_positive_flux_sum": None,
                    "pfba_negative_flux_sum": None,
                    "pfba_nonzero_reactions": None,
                })
                break

            try:
                psol = pfba(model)
                flux = psol.fluxes
            except Exception:
                flux = sol.fluxes

            interval_rows.extend(summarize_pathways(pathway_df, flux, cond, d0, d1, mode, status, obj_value))

            tag = f"{safe_name(cond)}_D{d0:g}_{d1:g}_{mode}"
            pathway_rxns = pathway_df[["pathway", "reaction", "reaction_name"] if "reaction_name" in pathway_df.columns else ["pathway", "reaction"]].copy()
            pathway_rxns["condition"] = cond
            pathway_rxns["day_start"] = d0
            pathway_rxns["day_end"] = d1
            pathway_rxns["interval"] = f"{d0:g}-{d1:g}"
            pathway_rxns["mode"] = mode
            pathway_rxns["flux"] = pd.to_numeric(flux.reindex(pathway_rxns["reaction"]), errors="coerce").fillna(0.0).values
            reaction_flux_rows.append(pathway_rxns)

            if args.run_fva:
                rxn_list = sorted(set(pathway_df["reaction"]))
                try:
                    fva = flux_variability_analysis(
                        model,
                        reaction_list=rxn_list,
                        fraction_of_optimum=args.fraction,
                        processes=1,
                    )
                    fva = fva.reset_index().rename(columns={"index": "reaction"})
                    fva["condition"] = cond
                    fva["day_start"] = d0
                    fva["day_end"] = d1
                    fva["interval"] = f"{d0:g}-{d1:g}"
                    fva["mode"] = mode
                    fva["range"] = fva["maximum"] - fva["minimum"]
                    fva = fva.merge(pathway_df[["pathway", "reaction"]].drop_duplicates(), on="reaction", how="left")
                    fva_rows.append(fva)
                except Exception as e:
                    warnings_all.append(pd.DataFrame([{
                        "condition": cond,
                        "day_start": d0,
                        "day_end": d1,
                        "mode": mode,
                        "reaction": "",
                        "issue": "pathway_fva_failed",
                        "detail": str(e),
                    }]))
            break

        if not used:
            print(f"[WARN] no successful mode for {cond} {d0:g}-{d1:g}")

    interval_summary = pd.DataFrame(interval_rows)
    reaction_fluxes = pd.concat(reaction_flux_rows, ignore_index=True) if reaction_flux_rows else pd.DataFrame()
    fva_detail = pd.concat(fva_rows, ignore_index=True) if fva_rows else pd.DataFrame()
    applied_detail = pd.concat(applied_all, ignore_index=True) if applied_all else pd.DataFrame()
    warnings_detail = pd.concat(warnings_all, ignore_index=True) if warnings_all else pd.DataFrame()

    interval_summary.to_csv(outdir / "pathway_interval_summary.csv", index=False, encoding="utf-8-sig")
    reaction_fluxes.to_csv(outdir / "pathway_reaction_fluxes.csv", index=False, encoding="utf-8-sig")
    applied_detail.to_csv(outdir / "pathway_applied_exchange_constraints.csv", index=False, encoding="utf-8-sig")
    warnings_detail.to_csv(outdir / "pathway_warnings.csv", index=False, encoding="utf-8-sig")

    if not fva_detail.empty:
        fva_detail.to_csv(outdir / "pathway_reaction_fva.csv", index=False, encoding="utf-8-sig")
        fva_summary = (
            fva_detail.groupby(["condition", "day_start", "day_end", "interval", "mode", "pathway"], as_index=False)
            .agg(
                fva_sum_range=("range", "sum"),
                fva_mean_range=("range", "mean"),
                fva_max_range=("range", "max"),
                n_fva_reactions=("reaction", "nunique"),
            )
        )
        fva_summary.to_csv(outdir / "pathway_fva_summary.csv", index=False, encoding="utf-8-sig")

        interval_summary = interval_summary.merge(
            fva_summary,
            on=["condition", "day_start", "day_end", "interval", "mode", "pathway"],
            how="left",
        )
        interval_summary.to_csv(outdir / "pathway_interval_summary.csv", index=False, encoding="utf-8-sig")

    if not interval_summary.empty:
        clone_summary = (
            interval_summary[interval_summary["pathway"] != "MODEL"]
            .groupby(["condition", "pathway"], as_index=False)
            .agg(
                mean_pfba_sum_abs_flux=("pfba_sum_abs_flux", "mean"),
                mean_pfba_net_flux=("pfba_net_flux", "mean"),
                mean_pfba_nonzero_reactions=("pfba_nonzero_reactions", "mean"),
                mean_fva_sum_range=("fva_sum_range", "mean") if "fva_sum_range" in interval_summary.columns else ("pfba_sum_abs_flux", "mean"),
            )
        )
        clone_summary.to_csv(outdir / "pathway_clone_summary.csv", index=False, encoding="utf-8-sig")

    print("[OK] saved:", outdir / "pathway_interval_summary.csv")
    print("[OK] saved:", outdir / "pathway_reaction_fluxes.csv")
    if args.run_fva:
        print("[OK] saved:", outdir / "pathway_reaction_fva.csv")
        print("[OK] saved:", outdir / "pathway_fva_summary.csv")
    print("[OK] saved:", outdir / "pathway_clone_summary.csv")


if __name__ == "__main__":
    main()
